; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v2.0.5 on Mon Oct 28 2019 20:36:57 GMT-0400 (Eastern Daylight Time)
G91               ; relative positioning
G1 Z5 F6000 S2    ; lift Z relative to current position
M913 X50
G1 S1 X-265 F4000 ; move quickly to X axis endstop and stop there (first pass)
G1 X5
M913 X100
G1 Z-5 F6000 S2   ; lower Z again
G90               ; absolute positioning

