; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.0.5 on Mon Oct 28 2019 20:36:58 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

